language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script:
  - export SERVER_USER=ubuntu
  - export APP_DIR=/home/ubuntu
  - if [ $TRAVIS_BRANCH == "develop" ]; then
      export SERVER_ADDRESS=$STAGING_IP_ADDRESS;
      export ENCRYPTED_DEPLOY_KEY=./staging_key.enc;
    fi
  - if [ $TRAVIS_BRANCH == "master" ]; then
      export SERVER_ADDRESS=$PRODUCTION_IP_ADDRESS;
      export ENCRYPTED_DEPLOY_KEY=./prod_key.enc;
    fi
  # Decrypt deploy key and add to SSH keys
  - openssl aes-256-cbc -K $encrypted_4df03c4dcdbb_key -iv $encrypted_4df03c4dcdbb_iv
      -in $ENCRYPTED_DEPLOY_KEY -out deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
